### ISSUE TITLE
Bug in monster movement?

### ISSUE THREAD

**Issue by ulfjack** [AluminumAngel/gloom#12]
I think that the monster movement in this scenario is incorrect:
https://gloom.aluminumangel.org/EYgMtAmYCEiAAAECBAgQIFwgPCBcIEQgVCAQhQSEC4QIhAqEB4QLhAiECgTCABgsXCBEIFQgEIYEhAwECBAgQIAAAQI

It shows me three options for the monster movement but the bottom option is closer to a legal hex that the monster can attack from. Note how the options change when removing one of the non-active monsters.

**Comment by ulfjack** [comment]
Here's another similar case which also looks incorrect:
https://gloom.aluminumangel.org/EZAMtAmgCEiAAAECBAgQIFwgPCBcIEQgVCAQhQSEC4QIhAoEwQAYAANgoHCBEIFQgfCAcIEQgVCBQBgSEDIQIECAAAECBAg

**Comment by AluminumAngel** [comment]
Thanks for the report. I'll take a look!

**Comment by AluminumAngel** [comment]
Ah, yeah. This is, I believe, due to an odd quirk in the rules.

Surprisingly, monster do not break ties when picking destinations based on which destination they can move closest to. Said another way, the monster considers all three destinations (or two, in the second link) as equally valid options.

Because of that, the players can choose which destination the monster will use. Once the destination is picked, the monster will move as close as possible. If there are multiple hexes equally close, the players can then again choose.

So, looking at the second link, the players are making two choices. First they pick which of two destinations. Then, if they pick the upper destination, they pick which of the two hexes the monster ends on.

I remember this because my algorithm used to work as you expect, but I updated it after a clarifying ruling was made. I'll try to find the ruling.

**Comment by AluminumAngel** [comment]
Here is the thread in which the ruling was given:  https://boardgamegeek.com/thread/2014493/monster-movement-question

Here is a (perhaps more understandable) discussion about the ruling:  https://www.reddit.com/r/Gloomhaven/comments/b3a1t1/help_me_understand_this_monster_movement_pic/

Here is the full FAQ for the game:  https://boardgamegeek.com/thread/1897763/official-faq-game-no-rules-questions-please

Closing. Let me know if you disagree after reading above.

**Comment by ulfjack** [comment]
Ah, thanks for the detailed analysis.
